---
- name: Main playbook
  hosts: all
  become: yes

  roles:
    - apt_upgrade
    - serviceuser

- hosts: bd
  become: yes
  roles:
    - setup_bd

- hosts: web
  become: yes
  roles:
    - setup_web
